version: 2.1 # CircleCI version
jobs:
  build:
    machine: #Linux machine instead of docker environment
      image: ubuntu-2004:2024.05.1
      docker_layer_caching: true
    working_directory: ~/mentoring # Default working directory
    steps:
      - run:
          name: Configure git to use HTTPS
          command: git config --global url."https://github.com/".insteadOf "git@github.com:"
      - checkout:
          path: ~/mentoring/
      - restore_cache:
          key: mentoring-dependency-cache-{{ checksum "src/package.json" }}
      - run:
          name: Install dependencies
          command: cd src/ && npm install #cd ../src/ && pwd &&
      - save_cache:
          key: mentoring-dependency-cache-{{checksum "src/package.json"}}
          paths:
            - ./src/node_modules
      - run:
          name: Cloning user service
          command: cd ../ && git clone https://github.com/ELEVATE-Project/user.git --branch dev --single-branch
      - restore_cache:
          key: user-dependency-cache-{{ checksum "../user/src/package.json" }}
      - run:
          name: Install User service dependencies
          command: cd ../user/src/ && npm install #cd ../src/ && pwd &&
      - save_cache:
          key: user-dependency-cache-{{checksum "../user/src/package.json"}}
          paths:
            - ../user/src/node_modules
      - run:
          name: Starting the docker containers
          command: |-
            cd dev-ops/ && docker-compose up -d && sleep 30
      - run:
          name: Running integration tests
          command: |-
            cd src/ && npm run test:integration
      - store_test_results:
          path: ./dev-ops/report
workflows:
  build-and-test: # This is the name of the workflow,
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build:
          filters:
            tags:
              only: \b(dev|develop|main)\b
