version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:2024.05.1
      docker_layer_caching: true
    working_directory: ~/mentoring
    steps:
      - run:
          name: Configure git to use HTTPS
          command: git config --global url."https://github.com/".insteadOf "git@github.com:"
      - checkout:
          path: ~/mentoring/
      - restore_cache:
          key: mentoring-dependency-cache-{{ checksum "src/package.json" }}
      - run:
          name: Install dependencies
          command: cd src/ && npm install
      - save_cache:
          key: mentoring-dependency-cache-{{checksum "src/package.json"}}
          paths:
            - ./src/node_modules
      
      # --- FIX STARTS HERE ---
      - run:
          name: Disable SSH rewrite for public repo clone
          # CircleCI forces HTTPS -> SSH in the checkout step. We must undo this to clone a public repo via HTTPS.
          command: git config --global --unset url."ssh://git@github.com".insteadOf || true
      # --- FIX ENDS HERE ---

      - run:
          name: Cloning user service
          # Now this HTTPS link will actually stay HTTPS
          command: cd ../ && git clone https://github.com/ELEVATE-Project/user.git --branch dev --single-branch
      - restore_cache:
          key: user-dependency-cache-{{ checksum "../user/src/package.json" }}
      - run:
          name: Install User service dependencies
          command: cd ../user/src/ && npm install
      - save_cache:
          key: user-dependency-cache-{{checksum "../user/src/package.json"}}
          paths:
            - ../user/src/node_modules
      - run:
          name: Starting the docker containers
          command: |-
            cd dev-ops/ && docker-compose up -d && sleep 30
      - run:
          name: Running integration tests
          command: |-
            cd src/ && npm run test:integration
      - store_test_results:
          path: ./dev-ops/report
workflows:
  build-and-test:
    jobs:
      - build:
          filters:
            tags:
              only: \b(dev|develop|main)\b